FROM node:12.16.1-alpine3.9

WORKDIR /usr/src/app
RUN yarn global add pg pg-hstore
RUN yarn add pg pg-hstore
COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . .

EXPOSE 3000
EXPOSE 3001
CMD ["yarn", "run", "start"]
