version: "3"
services:
  tipple:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  db-data:
  node_modules:
