FROM node:12.16.1-alpine3.9

# Set a working directory
WORKDIR /usr/src/app

# Set permissions for "node" user
RUN chown -R node:node /usr/src/app
RUN chmod 755 /usr/src/app

FROM BASE AS BUILD
COPY ./package.json .
COPY ./yarn.lock .

# Set NODE_ENV env variable to "production" for faster expressjs
ENV NODE_ENV production

COPY . .

# Run the container under "node" user by default
USER node

CMD [ "yarn", "start" ]
